"""Human-reviewable scientific inputs for the candidate-only SOC-F07 renderer.

These are audit judgments, not production records or an automated edge-discovery rule.
Sources were accessed on 2026-09-06/07 UTC (2026-09-06 local pilot date). Indexed
selected sections are identified honestly; no inaccessible full paper is claimed read.
"""
AUDIT = 'AUD-SOC-F07-AE-V1-20260906-001'
BASELINE = 'f0be9c24288bd128231e0d1243b34c03ad055906'
STAMP = '2026-09-07T02:46:39Z'
BRANCH = 'pilot/soc-f07-actions-events-v1'

# id, bibliographic title, authors, year, venue, DOI, accessed primary URL,
# access depth, evidence basis, locator, population/network, result, limitations.
SOURCES = [
('SRC-233','Birds of a Feather: Homophily in Social Networks','Miller McPherson; Lynn Smith-Lovin; James M. Cook',2001,'Annual Review of Sociology','10.1146/annurev.soc.27.1.415','https://www.annualreviews.org/doi/10.1146/annurev.soc.27.1.415','ABSTRACT','EVIDENCE_SYNTHESIS','Abstract','Multiple social settings; tie and group boundaries vary','Review describes similarity and social ties; it does not identify a metric-to-metric causal effect.','Selection, opportunity and influence must not be collapsed; no exact SOC-054 to SOC-057 estimate extracted.'),
('SRC-234','The Strength of Weak Ties','Mark S. Granovetter',1973,'American Journal of Sociology','10.1086/225469','https://snap.stanford.edu/class/cs224w-readings/granovetter73weakties.pdf','ABSTRACT','THEORETICAL_MECHANISTIC','Abstract; scanned PDF not text-reviewed','Interpersonal ties and information access','Theory motivates bridging mechanisms; weak ties, brokerage and betweenness are not synonyms.','Not an isolated causal estimate of structural constraint or cross-cluster tie prevalence.'),
('SRC-235','The spread of behavior in an online social network experiment','Damon Centola',2010,'Science','10.1126/science.1185231','https://ndg.asc.upenn.edu/wp-content/uploads/2016/04/Centola-2010-Science.pdf','SELECTED_FULL_TEXT','EXPERIMENTAL','Pages 1194-1196: design, results, reinforcement','1,528 participants; 12 anonymous health-buddy networks; fixed degree 6 or 8; three-week forum adoption experiment','Random topology assignment with degree held fixed supports context-bounded reinforcement and adoption differences.','Bundled topology contrast, not density manipulation; anonymous fixed ties and adoption notifications are not all friendship networks. Fourth/further notifications did not show detectable extra adoption in a small contrast.'),
('SRC-236','Identifying influential and susceptible members of social networks','Sinan Aral; Dylan Walker',2012,'Science','10.1126/science.1215842','https://pubmed.ncbi.nlm.nih.gov/22722253/','ABSTRACT','EXPERIMENTAL','Abstract','Online product notifications and connected users','Randomized messages distinguish influence and susceptibility in a specific product context.','Does not establish eigenvector centrality as influence or justify a universal position-to-behavior edge.'),
('SRC-237','A 61-million-person experiment in social influence and political mobilization','Robert M. Bond; Christopher J. Fariss; Jason J. Jones; Adam D. I. Kramer; Cameron Marlow; Jaime E. Settle; James H. Fowler',2012,'Nature','10.1038/nature11421','https://www.nature.com/articles/nature11421','ABSTRACT','EXPERIMENTAL','Abstract','Facebook political mobilization experiment','Randomized social messaging can affect behavior in a particular context.','Message exposure is not manipulation of network position; no social tie is an ontology Relationship.'),
('SRC-250','Changing climates of conflict: A social network experiment in 56 schools','Elizabeth Levy Paluck; Hana Shepherd; Peter M. Aronow',2016,'PNAS','10.1073/pnas.1514483113','https://www.pnas.org/doi/10.1073/pnas.1514483113','ABSTRACT','EXPERIMENTAL','Abstract','56 school networks; selected student referents and conflict intervention','Network-informed referent intervention supports testing seeding rather than directly manipulating centrality.','Referent selection, intervention content and outcomes are distinct; package evidence does not prove component efficacy.'),
('SRC-254','New Developments in Social Network Analysis','Daniel J. Brass',2022,'Annual Review of Organizational Psychology and Organizational Behavior','10.1146/annurev-orgpsych-012420-090628','https://www.annualreviews.org/doi/10.1146/annurev-orgpsych-012420-090628','ABSTRACT','EVIDENCE_SYNTHESIS','Abstract and indexed introduction','Organizational networks','Reviews network structure, behavior and brokerage developments.','Broad review is not direct evidence for contemporaneous density causing local clustering.'),
('SRC-255','Centrality in social networks: Conceptual clarification','Linton C. Freeman',1979,'Social Networks','10.1016/0378-8733(78)90021-7','https://www.sciencedirect.com/science/article/pii/0378873378900217','ABSTRACT','DEFINITIONAL_CALCULATIONAL','Abstract; full-paper download unavailable','Point centrality and graph centralization definitions','Distinguishes forms of centrality and corresponding graph centralization.','1978/79 issue dating; selected measure and benchmark required. No empirical causal claim.'),
('SRC-256','Network analysis in the social sciences','Stephen P. Borgatti; Ajay Mehra; Daniel J. Brass; Giuseppe Labianca',2009,'Science','10.1126/science.1165821','https://www.stats.ox.ac.uk/~snijders/siena/winterschool/BorgattiMehraBrassLabianca2009.pdf','SELECTED_FULL_TEXT','EVIDENCE_SYNTHESIS','Introduction and structural-mechanism discussion','Multiple social-network theories and settings','Network mechanisms require distinguishing ties, structure and flows.','Review is not independent replication of each cited experiment or direct metric-to-metric causality.'),
('SRC-260','Assortative mixing in networks','M. E. J. Newman',2002,'Physical Review Letters','10.1103/PhysRevLett.89.208701','https://arxiv.org/abs/cond-mat/0205405','ABSTRACT','THEORETICAL_MECHANISTIC','Abstract','Degree mixing, network examples and analytical models','Defines and analyzes degree assortativity.','Degree similarity is not automatically categorical segregation; model behavior is not empirical causal identification.'),
('SRC-269','Network Brokerage: An Integrative Review and Future Research Agenda','Seok-Woo Kwon; Emanuela Rondi; Daniel Z. Levin; Alfredo De Massis; Daniel J. Brass',2020,'Journal of Management','10.1177/0149206320914694','https://journals.sagepub.com/doi/abs/10.1177/0149206320914694','ABSTRACT','EVIDENCE_SYNTHESIS','Abstract','Organizational brokerage literature','Separates brokerage structures, behavior and dynamics.','Not direct proof that actor constraint changes network-wide cross-cluster tie prevalence.'),
('SRC-270','Homophily and Contagion Are Generically Confounded in Observational Social Network Studies','Cosma Rohilla Shalizi; Andrew C. Thomas',2011,'Sociological Methods & Research','10.1177/0049124111404820','https://pmc.ncbi.nlm.nih.gov/articles/PMC3328971/','SELECTED_FULL_TEXT','THEORETICAL_MECHANISTIC','Indexed abstract and introduction; direct page returned access challenge','Observational network identification','Latent homophily and contagion generally cannot be separated without strong assumptions or additional design leverage.','A methodological warning, not evidence that every influence effect is absent.'),
('SRC-497','A conceptual framework for action on the social determinants of health','World Health Organization',2010,'World Health Organization',None,'https://www.who.int/publications/i/item/9789241500852','METADATA','EVIDENCE_SYNTHESIS','Publication landing page; ISBN 9789241500852','Social determinants framework','Identity and broad framework relevance verified.','Full report not reviewed; direct support for INS-076 to network segregation remains unverified.'),
('SRC-505','Understanding and Addressing Misinformation About Science','National Academies of Sciences, Engineering, and Medicine',2025,'National Academies Press',None,'https://nap.nationalacademies.org/resource/27894/interactive/','DOCUMENTATION','EVIDENCE_SYNTHESIS','Interactive report summary','Science misinformation, audience and platform context','Summary discusses content environments and fragmentation.','Content exposure is not observed tie mixing; no direct TEC-029 to SOC-057 effect extracted.'),
('SRC-509','Composite canonical citation: Centola 2010 and Jackson & Yariv 2011 network diffusion review','As recorded in canonical source register',None,'Composite reference',None,'https://pubmed.ncbi.nlm.nih.gov/20813952/','METADATA','UNTESTED_HYPOTHESIS','Canonical citation versus linked PMID','Canonical citation alignment audit','Linked PMID resolves the Centola 2010 paper already represented by SRC-235.','Composite reference cannot count as two independent studies; second cited component unresolved. Preserve canonical register unchanged.'),
('001','Identification of Endogenous Social Effects: The Reflection Problem','Charles F. Manski',1993,'Review of Economic Studies','10.2307/2298123','https://doi.org/10.2307/2298123','ABSTRACT','THEORETICAL_MECHANISTIC','Publisher abstract','Group and individual behavior identification','Endogenous peer effects must be distinguished from contextual and correlated effects.','Reference-group specification and identifying assumptions matter; theory is not empirical influence evidence.'),
('002','Toward Causal Inference With Interference','Michael G. Hudgens; M. Elizabeth Halloran',2008,'Journal of the American Statistical Association','10.1198/016214508000000292','https://pmc.ncbi.nlm.nih.gov/articles/PMC2600548/','SELECTED_FULL_TEXT','THEORETICAL_MECHANISTIC','Indexed sections 2.1, 2.2, 4.2.1 and 6','Grouped treatments with within-group spillovers','Defines direct, indirect, total and overall effects under specified randomization and interference assumptions.','Partial interference between groups is an assumption, not a default fact about social networks.'),
('003','Effects of missing data in social networks','Gueorgi Kossinets',2006,'Social Networks','10.1016/j.socnet.2005.07.002','https://arxiv.org/abs/cond-mat/0306335','SELECTED_FULL_TEXT','MODEL_SIMULATION','Abstract and indexed Table 3; journal PDF sections','Collaboration network and missingness sensitivity experiments','Boundary, fixed-choice and nonresponse processes can bias network summaries differently.','Sensitivity simulations are not empirical causal effects. Preprint and journal article are one work.'),
('004','Centrality and network flow','Stephen P. Borgatti',2005,'Social Networks','10.1016/j.socnet.2004.11.008','https://sites.santafe.edu/~aaronc/courses/5352/readings/Borgatti_2005_CentralityAndNetworkFlow.pdf','SELECTED_FULL_TEXT','THEORETICAL_MECHANISTIC','Pages 55-60: flow typology','Network flow models','Centrality interpretation depends on the type and trajectory of flow.','Shortest-path, replication and transfer assumptions differ; simulations do not establish empirical brokerage effects.'),
('005','Tendencies toward triadic closure: Field experimental evidence','Mohsen Mosleh; Dean Eckles; David G. Rand',2025,'PNAS','10.1073/pnas.2404590122','https://pmc.ncbi.nlm.nih.gov/articles/PMC12260391/','SELECTED_FULL_TEXT','EXPERIMENTAL','Indexed abstract, experimental conditions and control contrasts','7,311 Twitter targets linked to 214 intermediary accounts; directed follows','Randomized open-triad cue/follow conditions increase reciprocal following relative to controls.','Common-follower signaling and reciprocal follow response are narrower than an unrestricted closure hazard. Control differences not detected do not prove equivalence; ethics of research accounts do not authorize practice.'),
('006','Short-term and long-term effects of a social network intervention on friendships among university students','Zsofia Boda; Timon Elmer; Andras Voros; Christoph Stadtfeld',2020,'Scientific Reports','10.1038/s41598-020-59594-z','https://www.nature.com/articles/s41598-020-59594-z','SELECTED_FULL_TEXT','QUASI_EXPERIMENTAL','Methods, longitudinal results and discussion','226 engineering freshmen; 99 introduction attendees; six waves; capped friendship nominations','Within-program group allocation produces early friendship differences that diminish over time.','Attendance nonrandom; group constraints and interference matter. Friendship incidence is not conditional triadic closure; SAOM is not proof of mediation.'),
('007','Dynamic social networks promote cooperation in experiments with humans','David G. Rand; Samuel Arbesman; Nicholas A. Christakis',2011,'PNAS','10.1073/pnas.1108243108','https://pmc.ncbi.nlm.nih.gov/articles/PMC3228461/','SELECTED_FULL_TEXT','EXPERIMENTAL','Indexed abstract and discussion','Repeated online cooperation game with constrained link updating','Fluid partner updating can sustain cooperation while fixed/random/infrequent updating comparisons decay.','Updating opportunity, selection and topology co-evolve; cannot isolate a causal local-clustering coefficient.'),
('008','Social network targeting to maximise population behaviour change: a cluster randomised controlled trial','David A. Kim; Alison R. Hwong; Derek Stafford; D. Alex Hughes; A. James OMalley; James H. Fowler; Nicholas A. Christakis',2015,'The Lancet','10.1016/S0140-6736(15)60095-2','https://pmc.ncbi.nlm.nih.gov/articles/PMC4638320/','SELECTED_FULL_TEXT','EXPERIMENTAL','Indexed abstract and results','32 Honduran villages; 5,773 participants; nominated/random/high-degree seeds','Network nomination benefits were outcome-dependent; high-degree targeting was not uniformly superior.','Seed selection does not manipulate degree; product, nomination, implementation and interference limit transfer.'),
('009','Social network interventions for health behaviours and outcomes: A systematic review and meta-analysis','Ruth F. Hunter; Kayla de la Haye; Jennifer M. Murray; Jennifer Badham; Thomas W. Valente; Mike Clarke; Frank Kee',2019,'PLOS Medicine','10.1371/journal.pmed.1002890','https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002890','SELECTED_FULL_TEXT','EVIDENCE_SYNTHESIS','Abstract, methods and results tables','Health network intervention studies; varied populations and outcomes','Network intervention evidence is heterogeneous across approaches and outcomes.','Review includes primary-study evidence that must not be counted again as replication; no exact SOC-102 pooled estimate extracted.'),
('010','Displaying Things in Common to Encourage Friendship Formation: A Large Randomized Field Experiment','Tianshu Sun; Sean J. Taylor',2019,'arXiv preprint','10.48550/arXiv.1905.02762','https://arxiv.org/abs/1905.02762','ABSTRACT','EXPERIMENTAL','Author-deposited abstract','Online nonfriend profile browsing and verified common attributes','Randomized prominence of shared attributes can encourage friendship formation.','Not an open-triad risk-set experiment; journal-version bibliographic mapping not relied upon.'),
('011','A natural experiment of social network formation and dynamics','Tuan Q. Phan; Edoardo M. Airoldi',2015,'PNAS','10.1073/pnas.1404770112','https://pmc.ncbi.nlm.nih.gov/articles/PMC4450406/','SELECTED_FULL_TEXT','QUASI_EXPERIMENTAL','Indexed methods and discussion','Longitudinal college Facebook networks around Hurricane Ike','Disruption is associated with more closed local relations and fewer bridging/public exchanges in affected networks.','Nonrandom disaster exposure; displacement, simultaneous behavior and boundary change. Transitivity is not closure hazard.'),
('012','Proximity can induce diverse friendships: A large randomized classroom experiment','Julia M. Rohrer; Tamas Keller; Felix Elwert',2021,'PLOS ONE','10.1371/journal.pone.0255097','https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0255097','SELECTED_FULL_TEXT','EXPERIMENTAL','Abstract and methods','2,966 pupils in 182 classrooms; assigned seating over a semester','Assigned proximity can affect nominated friendship formation across some social boundaries.','Seating distance is not ENV-034 personal-space encroachment and friendship is not conditional triadic closure.'),
('013','Chronic illness and social network bridging in later life','Tianyao Qu',2023,'Social Networks','10.1016/j.socnet.2023.01.007','https://pmc.ncbi.nlm.nih.gov/articles/PMC10655771/','SELECTED_FULL_TEXT','OBSERVATIONAL_LONGITUDINAL','Indexed abstract and introduction','1,555 older adults; two NSHAP waves; kin/nonkin ego networks','Chronic illness is associated with later differences in bridging.','Health selection, capped ego nominations and confounding remain; mediation wording is not transmitted causal-effect evidence.'),
('014','Introduction to stochastic actor-based models for network dynamics','Tom A. B. Snijders; Gerhard G. van de Bunt; Christian E. G. Steglich',2010,'Social Networks','10.1016/j.socnet.2009.02.004','https://www.stats.ox.ac.uk/~snijders/SnijdersSteglichVdBunt2009.pdf','SELECTED_FULL_TEXT','THEORETICAL_MECHANISTIC','Abstract and model-selection guidance','Directed longitudinal networks and jointly changing behavior','Models can jointly represent endogenous network dynamics and changing actor attributes.','Model assumptions, selection specification, wave spacing and time homogeneity require examination; parameters are not automatically identified causal effects.'),
('015','The political effects of Xs feed algorithm','Germain Gauthier; Roland Hodler; Philine Widmer; Ekaterina Zhuravskaya',2026,'Nature','10.1038/s41586-026-10098-2','https://www.nature.com/articles/s41586-026-10098-2','SELECTED_FULL_TEXT','EXPERIMENTAL','Abstract and methods/results','4,965 completing US participants; 2023 seven-week feed experiment','Enabling the feed affected some follows and attitudes; disabling did not produce symmetric reversal.','No detected effects on some polarization/partisanship outcomes; feed bundle is not isolated filtering restrictiveness or whole-network segregation.'),
('016','Mixing patterns in networks','M. E. J. Newman',2003,'Physical Review E','10.1103/PhysRevE.67.026126','https://arxiv.org/abs/cond-mat/0209450','ABSTRACT','DEFINITIONAL_CALCULATIONAL','Abstract','Categorical and scalar mixing measures','Specifies alternatives for measuring mixing and their baseline dependence.','Definitions and models are not empirical direction-of-causation evidence.'),
('017','Fundamental principles of network formation among preschool children','David R. Schaefer; John M. Light; Richard A. Fabes; Laura D. Hanish; Carol Lynn Martin',2010,'Social Networks','10.1016/j.socnet.2009.04.003','https://pmc.ncbi.nlm.nih.gov/articles/PMC2811339/','SELECTED_FULL_TEXT','OBSERVATIONAL_LONGITUDINAL','Indexed methods 4.1 and discussion 6','195 preschool children in 11 Head Start classrooms; observation over a school year','Transitivity-related formation patterns evolve during emerging peer networks.','Composition change and model assumptions; not randomized biological development or proof of a universal closure trajectory.'),
('018','UCINET Help: Network > Centrality > Degree','Analytic Technologies',None,'UCINET maintainer documentation',None,'https://www.analytictech.com/ucinet/help/3ava_zr.htm','DOCUMENTATION','DEFINITIONAL_CALCULATIONAL','Indexed DESCRIPTION and COMMENTS; direct open unavailable','Binary specified networks and selected degree centralization','Degree centralization uses the distribution of node degree and a maximum-possible benchmark.','Not every centralization is degree-based; directedness, loops, normalization and valued-network versions require explicit selection. No single ego degree determines network centralization.'),
]

# disposition, precise review proposal, principal evidence, unresolved issue.
EXISTING = {
'REL-RDS-0004': ('RETAIN_AS_IS','Retain equivalence only for matched active-contact tie definition, binary unweighted undirected graph, focal actor, boundary and window.',['SRC-255'],'No universal equivalence between personal-network size and every degree statistic.'),
'REL-RDS-0006': ('RETAIN_AS_IS','Retain RELATED_METRIC; cross-cluster ties and member cross-group friendships have different denominators.',['SRC-233'],'Not an equality or causal link; no duplicate V1 proposition needed.'),
'REL-RDS-0013': ('RETAIN_AS_IS','Retain NARROWER_THAN: closure among eligible open triads is a restricted tie-formation process.',['005','017'],'Risk set and interval must match; narrower-than does not imply equal rates.'),
'REL-SOC-031': ('RETYPE_CANDIDATE','Consider a noncausal conditional structural comparison of SOC-052 and SOC-053, not CAUSES; no exact replacement predicate approved.',['SRC-254','SRC-256','SRC-235','003'],'Global density and ego clustering share adjacency inputs but neither universally determines the other. Same-time summary contrast lacks independent temporal mechanism.'),
'REL-SOC-032': ('RETYPE_CANDIDATE','Consider noncausal baseline-qualified mixing/segregation comparison, retaining SOC-054 and SOC-057 as distinct measures.',['SRC-233','SRC-260','SRC-270','016'],'Degree assortativity is not categorical segregation; group attributes, opportunities and null model unresolved. Shared mixing matrix can induce dependence.'),
'REL-SOC-033': ('RETYPE_CANDIDATE','Consider noncausal scope-qualified association/related-metric representation of constraint and cross-cluster ties; do not force inverse causality.',['SRC-234','SRC-269','004'],'Actor contact weights versus network/actor community-crossing denominator; partitions and scope may differ. Mechanism of brokerage is not the constraint formula acting on another summary.'),
'REL-SOC-034': ('RETYPE_CANDIDATE','Consider conditional noncausal mixing comparison; preserve distinction between cluster partitions and social-group segregation.',['SRC-233','SRC-234','SRC-269','016'],'Shared edge counts and complementary mixing can be mathematical; arbitrary communities need not equal groups. No independent lag or mechanism established.'),
'REL-SOC-035': ('REVISION_CANDIDATE','Propose a bounded topology-to-redundant-adoption-notification claim under fixed degree, stable assigned ties and a specific contagion task; whether SOC-053 to SOC-061 is exact enough remains unresolved.',['SRC-235','SRC-256','001','002'],'Clustering bundles path redundancy; SOC-061 uses independently reinforcing neighbors, not independent randomized messages. Preserve existing edge; no universal magnitude, lag or pathway.'),
'REL-INS-047': ('REVISION_CANDIDATE','Propose restricting institutional segregation to specified assignment/contact constraints preceding measured between-group tie mixing; exact institution, groups, metric and identification remain research-needed.',['SRC-497','SRC-509','012'],'Framework and mismatched composite diffusion source are not direct identified institutional-segregation evidence. Assignment can be a common cause, not an autonomous RDS effect.'),
'REL-TEC-050': ('RESEARCH_NEEDED','Keep existing proposition unchanged pending direct evidence on filtering restrictions and later social-tie segregation.',['SRC-505','SRC-509','015'],'Content availability, follows and whole-network segregation are distinct; new feed experiment is bundled and asymmetric, not exact universal TEC-029 effect.'),
}

# Explicitly examined propositions, not an automatic edge-generation queue.
# id, proposition, semantic triage, disposition, reason, source keys, consulted endpoint IDs
HYPOTHESES = [
('H01','Degree causes itself through tie count','CAUSAL','REJECTED','Identity/formula contribution, not an independent force.',['SRC-255'],['SOC-049']),
('H02','Density causes local clustering at the same instant','CAUSAL','REJECTED','Existing retype path REL-SOC-031; shared adjacency and counterexamples preclude automatic causal expansion.',['SRC-235','003'],['SOC-052','SOC-053']),
('H03','Assortativity and segregation are universally causally interchangeable','CAUSAL','REJECTED','Degree versus group attributes and baseline-dependent mixing; existing retype path.',['SRC-260','016'],['SOC-054','SOC-057']),
('H04','Constraint causes fewer cross-cluster ties by formula alone','CAUSAL','REJECTED','Shared graph construction; existing review path, no new duplicate.',['SRC-269'],['SOC-055','SOC-056']),
('H05','Clustering causes cooperation prevalence','CAUSAL','RESEARCH_NEEDED','Fluid-network experiment changes partner choice and selection, not isolated local clustering.',['007','002','SRC-270'],['SOC-053','SOC-034']),
('H06','Betweenness causes later information access','CAUSAL','RESEARCH_NEEDED','Flow mechanism plausible, but geodesic metric and exact informational endpoint/temporal identification unresolved.',['004','SRC-234'],['SOC-050']),
('H07','Eigenvector centrality is social influence','SEMANTIC','REJECTED','Estimator and influence construct differ; randomized influence evidence does not establish equivalence.',['SRC-236','004'],['SOC-051']),
('H08','Degree-based centralization derives from degree distribution','DERIVATIONAL','REVIEW_READY','Retain one conditional derivation candidate, requiring whole distribution, graph boundary and benchmark.',['SRC-255','018'],['RDS-0006','SOC-049']),
('H09','Personal network size universally equals degree','SEMANTIC','REJECTED','Existing conditional mapping already governs only matched scope; no duplicate.',['SRC-255'],['SOC-049','SOC-024']),
('H10','Dense network makes exposure cause adoption more strongly','MODERATION','RESEARCH_NEEDED','No exact governed exposure-to-outcome edge with aligned moderator experiment established; density is not clustering.',['SRC-235','002'],['SOC-052','SOC-058']),
('H11','Centrality to exposure to behavior is a demonstrated pathway','CAUSAL_PATHWAY','RESEARCH_NEEDED','Reachability and separately supported segments are not transmitted-effect evidence.',['SRC-236','001','SRC-270'],['SOC-049','SOC-058']),
('H12','Network rewiring directly changes degree RDS','CAUSAL','BLOCKED_NEEDS_GOVERNANCE_INPUT','Real tie configuration can change, but no full canonical network-state Driver target; rate Drivers do not encode adjacency.',['007','SRC-235'],['SOC-049','SOC-101','SOC-103']),
('H13','Friendship addition edits a PSYWERX Relationship','SEMANTIC','REJECTED','Real dyadic tie is not a scientific proposition.',['SRC-256'],[]),
('H14','Peer correlation proves contagion','CAUSAL','REJECTED','Reflection, homophily, latent traits and shared environment defeat that inference.',['001','SRC-270'],['SOC-058']),
('H15','Cultural homophily causes assortativity','CAUSAL','RESEARCH_NEEDED','Similarity, opportunity, selection and influence not separated; attribute and endpoint operationalization unresolved.',['SRC-233','SRC-270'],['SOC-054']),
('H16','Illness causes less network bridging','CAUSAL','RESEARCH_NEEDED','Longitudinal association in capped older-adult ego networks does not eliminate health selection or identify exact SOC-056.',['013'],['SOC-056']),
('H17','Seating proximity causes closure rate','CAUSAL','RESEARCH_NEEDED','Random seating affects friendship, not open-triad hazard; ENV-034 is personal-space encroachment, not geometric distance.',['012'],['SOC-102','ENV-034']),
('H18','Algorithmic filtering causes network segregation','CAUSAL','RESEARCH_NEEDED','Existing REL-TEC-050 review, not a duplicate edge; feed/exposure/follow mixing not same construct.',['015','SRC-505'],['SOC-057','TEC-029']),
('H19','Closeness causes resource control','CAUSAL','RESEARCH_NEEDED','Flow and resource access mechanism needs matching path assumptions and exact resource-control construct.',['004','SRC-269'],['RDS-0005','SOC-046']),
('H20','Component fragmentation changes directly through node deletion','CAUSAL','BLOCKED_NEEDS_GOVERNANCE_INPUT','RDS is recalculated; node/boundary operation lacks a complete Driver target; blocked derivation metadata preserved.',['003'],['RDS-0007']),
('H21','A static position TRANSITIONS_TO later behavior','TEMPORAL','REJECTED','Different constructs are not qualified states of one entity; dynamic causality needs independent evidence.',['014'],['SOC-050']),
('H22','Closure causes local clustering purely by completing triangles','CAUSAL','REJECTED','Triangle-count contribution to snapshot statistic is derivation, not an extra propagated effect; interval and denominator differ.',['017'],['SOC-102','SOC-053']),
('H23','Observed storm proves all later tie effects','CAUSAL','REJECTED','Occurrence verification cannot identify every consequence; quasi-experimental comparison still has assumptions.',['011'],[]),
('H24','High-degree seeding is universally best','CAUSAL','REJECTED','Outcome-specific trial and review do not support universal superiority or recommendation.',['008','009'],['SOC-049']),
('H25','Social isolation equals zero degree','SEMANTIC','REJECTED','Observed isolate in chosen boundary is not perceived isolation/belonging; ties outside sample may exist.',['003'],['SOC-049','PSY-020']),
('H26','Development raises triadic closure','CAUSAL','RESEARCH_NEEDED','Observed preschool network emergence is not isolated biological maturation; no canonical developmental Driver substituted.',['017','014'],['SOC-102']),
('H27','Betweenness and degree association is construction-free','ASSOCIATION','RESEARCH_NEEDED','Shared network and graph size require conditional operationalizations and a scoped empirical estimate.',['SRC-255','004'],['SOC-050','SOC-049']),
('H28','Network metrics realize the latent real network without error','REALIZATION','REJECTED','Representation, estimator and real network are distinct; missing ties and boundaries matter.',['003'],['SOC-052']),
('H29','A network is compositionally constituted by its centrality scores','COMPOSITIONAL','REJECTED','Scores do not uniquely specify ties; no composition edge from a metric to real network.',['SRC-255'],['SOC-049']),
]

# Names are reusable operations; source evidence does not confer efficacy/actionability.
ACTIONS = [
('001','Display a verified common-follower cue with a follow invitation',['TEC','INF'],True,['TECHNOLOGICAL_CHANGE','INFORMATIONAL_EXPOSURE','DELIBERATE_INTERVENTION'],['005'],'Expose a genuine intermediary-follow relation in a specified invitation protocol; no fake social proof.','Mutual-follower cue and reciprocal follow may operationalize a restricted open triad, not the general SOC-102 risk set.'),
('002','Assign introduction-session participants to small contact groups',['INS','SOC'],True,['INSTITUTIONAL_STRUCTURAL_CHANGE','SOCIAL_NETWORK_PROCESS','DELIBERATE_INTERVENTION'],['006'],'Allocate consenting participants to a bounded introduction group; identity is allocation, not its outcomes.','Attendance selection, group composition, tie nomination caps and closure-risk-set mismatch.'),
('003','Enable participant-controlled partner-link revision in a bounded interaction protocol',['TEC','SOC'],True,['TECHNOLOGICAL_CHANGE','SOCIAL_NETWORK_PROCESS','DELIBERATE_INTERVENTION'],['007'],'Permit defined requests to revise interaction partners under a stated protocol.','Link choice, selection and topology co-evolve; not a direct metric manipulation or universal cooperation treatment.'),
('004','Assign a specified health-buddy contact topology',['TEC','SOC'],True,['SOCIAL_NETWORK_PROCESS','DELIBERATE_INTERVENTION'],['SRC-235'],'Allocate protocol-defined anonymous contact links before a specified communication task.','Degree, boundary and topology fixed by protocol; artificial ties are not ordinary friendship or independent metric causes.'),
('005','Seed a bounded behavior message through nominated network referents',['SOC','INF'],True,['INFORMATIONAL_EXPOSURE','DELIBERATE_INTERVENTION'],['008','SRC-250','009'],'Select nominated referents and deliver specified communication to them; retain content and selection as protocol details.','Seeding is not changing degree; no identity efficacy, optimality or component inference.'),
('006','Storm-related disruption of campus contact opportunities',['ENV','INS'],False,['EXTERNAL_SHOCK','ENVIRONMENTAL_EXPOSURE','SOCIAL_NETWORK_PROCESS'],['011'],'Disruption of access and contact opportunities associated with a storm; not an occurrence-ingestion object.','Displacement, institutional responses, composition change and nonrandom exposure confound universal transfer.'),
('007','Allocate classroom seats for sustained assigned proximity',['INS','ENV'],True,['INSTITUTIONAL_STRUCTURAL_CHANGE','DELIBERATE_INTERVENTION'],['012'],'Assign seats under a specified classroom protocol, without promising friendship or closure.','Consent, accessibility, stigma and educational constraints; geometric proximity is not personal-space encroachment.'),
('008','Display verified shared profile attributes to a prospective contact',['TEC','INF'],True,['TECHNOLOGICAL_CHANGE','INFORMATIONAL_EXPOSURE','DELIBERATE_INTERVENTION'],['010'],'Make existing shared attributes visible; distinct from common-neighbor signaling.','Privacy, truthful disclosure and platform population limits; not a triadic-closure estimate.'),
]

RDS_NOTES = {
'SOC-049': ('Ego degree; raw or normalized incidence','Incident adjacency row/column; n-1 or specified opportunity denominator; loops, directedness and weights matter.','Tie allocation/addition/deletion and node sampling alter inputs; no complete network-state Driver.','004,007,008'),
'SOC-050': ('Ego shortest-path betweenness','All relevant shortest paths and geodesic multiplicity; disconnected paths, weights and normalization change meaning.','Rewiring or node loss changes paths; brokerage behavior is not betweenness.','003,004'),
'SOC-051': ('Eigenvector-based ego position','Whole adjacency and chosen eigenvector/normalization; disconnected components and directed/weighted conventions matter.','Rewiring can redistribute scores without independently manipulating social influence.','004'),
'SOC-052': ('Whole-network density','Observed ties over possible ties; n, directedness, loops, multiplex collapse and boundary determine denominator.','Node admission/removal and contact restrictions can change numerator AND denominator.','003,004,007'),
'SOC-053': ('Ego neighborhood clustering','Triangles among selected neighbors over eligible pairs; degree<2 convention unresolved at analysis time.','Closing a tie changes triangle inputs; conditional closure rate is not a static clustering coefficient.','004,007'),
'SOC-054': ('Attribute-specific mixing','Mixing matrix and expected baseline; categorical/degree/scalar attribute choice changes construct.','Assignment, selection and changing attributes affect matrix; preference cannot be inferred from mixing.','002,007'),
'SOC-055': ('Actor structural constraint','Actor contacts and contact-to-contact weights; concentration and redundancy normalization require named formula.','Brokerage opportunities may change when contacts change; behavior and path-based betweenness are distinct.','003,004'),
'SOC-056': ('Tie-level cross-community share','Cross-community edges over observed eligible ties; community detection/assignment and scale essential.','A partition change alone changes score without changed ties; member exposure is a separate denominator.','003,006'),
'SOC-057': ('Group mixing relative to opportunity','Group assignment and observed mixing with size/opportunity baseline; not any algorithmic community partition.','Institutional assignment and contact configuration may matter; denominator/group changes can be mechanical.','002,006,007'),
'RDS-0005': ('Distance-based ego closeness','Path-distance matrix, focal actor, unreachable-node convention and normalization externally specified.','Node loss, missing ties and routing assumptions alter paths; no universally best centrality.','003,004'),
'RDS-0006': ('Network-level centralization','Distribution of one selected node centrality and benchmark/maximum; selection remains external and incomplete.','Degree-based case can derive from degree distribution, not a single actor value; other centralizations differ.','003,004'),
'RDS-0007': ('Component fragmentation','Connected-component structure and selected metric: component count/giant share/isolate share/unreachable pairs are not identical.','Boundary expansion, node removal or bridges change components; no direct RDS manipulation.','003,006'),
}

# These are actual search concepts/systems, not a claimed formal systematic review.
SEARCHES = [
('Q01','Existing sources before gaps','Centola 2010 network experiment PDF; Freeman centrality clarification; Brass network review; Kwon brokerage; Granovetter weak ties; Newman assortativity; WHO institutional segregation; National Academies filtering','SRC-233 SRC-234 SRC-235 SRC-254 SRC-255 SRC-256 SRC-260 SRC-269 SRC-497 SRC-505 SRC-509','Canonical alignment; broad/composite sources cannot stand in for direct evidence.'),
('Q02','Network identification and observation','Manski reflection problem; Hudgens Halloran interference; Shalizi Thomas homophily contagion; Kossinets missing network data; Borgatti centrality flow; Snijders actor based dynamics','001 002 003 004 014 SRC-270','Methods establish assumptions, not empirical effects.'),
('Q03','Exact Driver and Social/Technological/Informational mechanisms','triadic closure randomized field experiment common follower; introduction group assignment university friendships; displaying things in common friendship experiment','005 006 010','Screen for open-triad risk set rather than all friendship incidence.'),
('Q04','Network interventions and relationship modification','dynamic networks cooperation experiment; network seeding trial high degree; social network intervention systematic review; Paluck school referents; Aral influence; Bond mobilization','007 008 009 SRC-250 SRC-236 SRC-237','Direct topology/position targets excluded; selection and message effects separated.'),
('Q05','Environmental/Institutional origins','randomized classroom seating friendships; hurricane disaster social network formation natural experiment','011 012','Geometric contact opportunity and transitivity do not equal exact existing Driver/RDS effects.'),
('Q06','Biological/Psychological/Cultural and unintended processes','aging chronic illness social network bridging longitudinal; preschool triadic closure development; cultural homophily network formation; personality selection triadic closure longitudinal','013 017 SRC-233 SRC-270','Illness/development/traits and cultural selection remain observational or target-misaligned; no causal population quota.'),
('Q07','Technological cross-Layer counterevidence','algorithm feed experiment social ties follow segregation; X feed algorithm political effects randomized','015 SRC-505','Recent follow behavior evidence does not repair exact legacy filtering-to-segregation claim.'),
('Q08','Derivation verification and candidate deduplication','Freeman degree centralization UCINET help; Newman categorical mixing patterns','018 016 SRC-255','Conditional degree-centralization dependency only; all other external inputs retained.'),
]

# Additional design extraction for direct empirical leads. Unextracted details stay
# explicitly unknown rather than being reverse-engineered from a title or result.
SOURCE_DESIGNS = {
'SRC-235': {'nodes':'Consenting health-interest participants in assigned experimental networks','ties':'Undirected assigned anonymous health-buddy links; adoption notifications, not ordinary friendship',
 'boundary':'12 closed networks across six trials; fixed degrees; no participant rewiring','exposure':'Random assignment to clustered lattice versus random topology at matched degree',
 'comparator':'Random topology with same degree condition','outcome':'Forum registration/adoption and number of preceding adoption signals','timing':'Assigned topology before adoption; three-week observation',
 'identification':'Randomized topology; interference is part of treatment, not independent unit noise','confounds':'Degree held fixed, but topology dimensions remain bundled','limitations':'No independent manipulation of density, isolated local clustering or generic reinforcement.'},
'005': {'nodes':'Experimental accounts A, intermediary accounts B and target users C','ties':'Directed follows; response is C following A after A follows C',
 'boundary':'Selected Twitter targets with experimentally arranged A-B-C open-triad conditions','exposure':'Follow invitation from account with experimentally arranged common-neighbor relation',
 'comparator':'Different-account or severed intermediary-follow control configurations','outcome':'Reciprocal following completing the directed relation','timing':'Intermediary condition before invitation and observed response',
 'identification':'Random assignment of experimental account/triad conditions','confounds':'Restricted platform risk set and cue visibility; population selection limits transport','limitations':'Not a free-running open-triad hazard for all actors/tie types.'},
'006': {'nodes':'Engineering freshmen in one cohort','ties':'Directed friendship nominations, capped at 20; repeated waves',
 'boundary':'226-student cohort; 99 program attendees; participation nonrandom','exposure':'Small-group introduction allocation within program constraints',
 'comparator':'Students not sharing introduction groups; other attendance comparisons not randomized','outcome':'Nominated friendship formation and persistence','timing':'Six waves over roughly 2-14 months',
 'identification':'Constrained group assignment plus longitudinal analysis; authors discuss quasi-experimental interference','confounds':'Attendance selection, group/gender constraints, changing ties and model assumptions','limitations':'Friendship incidence and snapshot closure do not directly estimate SOC-102.'},
'007': {'nodes':'Human online experimental participants','ties':'Permitted interaction partner links in repeated cooperation game',
 'boundary':'Experiment-specific fixed/random/slow/fluid updating networks','exposure':'Opportunity to update partner links at different rates',
 'comparator':'Fixed, random or infrequently updated partner networks','outcome':'Cooperation over repeated rounds','timing':'Repeated rounds with jointly changing ties and cooperation',
 'identification':'Experimental updating conditions; choice/selection remains mechanism within treatment','confounds':'Selection, topology and behavior not separately randomized','limitations':'Cannot assign resulting benefit to a single derived local-clustering metric.'},
'008': {'nodes':'Residents of 32 Honduran villages','ties':'Survey-nominated social contacts used to select seeds',
 'boundary':'Village intervention populations; 5,773 participants','exposure':'Random, highest-degree or nominated-friend seeding strategy',
 'comparator':'Other assigned seeding strategies','outcome':'Multivitamin and chlorine product adoption, separately','timing':'Seeding before observed uptake','identification':'Cluster randomized strategy trial',
 'confounds':'Interference, implementation, product and nomination selection; not degree manipulation','limitations':'Outcome heterogeneity and lack of universal high-degree advantage.'},
'011': {'nodes':'University Facebook users in affected and comparison institutions','ties':'Observed friendship/activity traces, not complete offline networks',
 'boundary':'Sampled college networks around Hurricane Ike','exposure':'Disaster-associated disruption in affected university networks',
 'comparator':'Comparison institutions/time periods','outcome':'Network closure/bridging and communication patterns','timing':'Longitudinal observations before/after disruption',
 'identification':'Natural-experiment comparison, not randomized disaster exposure','confounds':'Exposure selection, displacement, node attrition, composition and concurrent responses','limitations':'Transitivity and post-disruption patterns not an identified conditional closure hazard.'},
'012': {'nodes':'Pupils in 182 classrooms','ties':'Nominated friendships; assigned classroom seats separate from measured ties',
 'boundary':'2,966 pupils, grades 3-8 in participating schools','exposure':'Randomized seat-neighbor assignment','comparator':'Nonadjacent assigned classmates',
 'outcome':'Friendship nominations and subgroup differences','timing':'Semester exposure before friendship measurement','identification':'Within-classroom randomized proximity',
 'confounds':'Other classroom contacts and interference; generalization outside classrooms untested','limitations':'No open-triad conditional risk set; geometric distance not preferred-space encroachment.'},
'013': {'nodes':'Older NSHAP respondents and nominated alters','ties':'Capped ego-network nominations including kin/nonkin','boundary':'1,555 respondents observed at two waves',
 'exposure':'Reported chronic illness','comparator':'Different health states within longitudinal analytic sample','outcome':'Kin/nonkin bridging measures',
 'timing':'Two-wave longitudinal comparison','identification':'Observational longitudinal, not randomized','confounds':'Health selection, latent attributes, attrition and capped nominations',
 'limitations':'Reported mediation is not a demonstrated causal pathway; no exact triadic closure effect.'},
'015': {'nodes':'Participating US X users and followed accounts','ties':'Follow behavior; feed exposures are separate','boundary':'4,965 completing participants in 2023 seven-week experiment',
 'exposure':'Enable/disable algorithmic feed conditional on initial feed setting','comparator':'Assigned alternative feed setting within baseline-setting groups','outcome':'Selected follows, attitudes and polarization/partisanship measures',
 'timing':'Seven-week intervention and reported follow-up','identification':'Randomized feed setting; treatment bundle not single filtering component',
 'confounds':'Noncompliance/attrition, initial-setting strata and scope of users; direction asymmetric','limitations':'No full-network segregation measure; no detected effects on some distinct political outcomes.'},
'017': {'nodes':'195 preschool children across 11 Head Start classrooms','ties':'Observed peer interactions across a school year','boundary':'Classroom networks with enrollment and withdrawal',
 'exposure':'Naturally emerging peer networks and observed structural tendencies','comparator':'Model-based time/structural contrasts, not randomized developmental exposure',
 'outcome':'Formation/transitivity patterns','timing':'Longitudinal school-year observations','identification':'Observational network model',
 'confounds':'Composition change, age, selection, shared environment and model specification','limitations':'Not biological maturation causing exact SOC-102; theoretical model parameters are not graph weights.'},
}
